[tool.poetry]
name = "pinnwand"
version = "1.4.0"
description = "Straightforward pastebin software."
authors = ["Simon de Vlieger <cmdr@supakeen.com>"]
license = "MIT"
readme = "README.md"
keywords = ["pastebin", "python", "tornado"]
repository = "https://github.com/supakeen/pinnwand"
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
]
packages = [
    { include = "pinnwand", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.7,<4"
tornado = "^6.1"
pygments = "^2.11"
sqlalchemy = "^1.4"
click = "^8.0"
docutils = "^0.17"
pygments-better-html = "^0.1.0"
token-bucket = "^0.3.0"
tomli = "^2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0"
coverage = "^6.3"
black = "^22.3"
pytest-cov = "^3.0"
pre-commit = "^2.18"
flake8 = "^4.0"
mypy = "^0.942"
types-docutils = "^0.19.1.1"
isort = "^5.10.1"

[tool.black]
line-length = 80
target_version = ["py36"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.eggs
  | \.mypy_cache
  | \.tox
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[tool.poetry.scripts]
pinnwand = 'pinnwand.__main__:main'

[tool.pytest.ini_options]
pythonpath = ["src"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
