name: Vulnerability Scanners

on:
  push:
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit
    - name: Check with bandit
      run: bandit -r src/pinnwand
  pip-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pip-audit
    - name: Check with pip-audit
      run: pip-audit --requirement requirements.txt
